### ISSUE TITLE
ATST: Could you share finetuning details, please?

### ISSUE THREAD

**Issue by daisukelab** [Audio-WestlakeU/audiossl#5]
Dear authors,

First, congratulations on the great results you have achieved.
These are wonderful numbers!
(BTW, I think I should clarify that I am the author of BYOL-A. Thank you for making progress!)

I'm trying to replicate your results, especially finetuning of VoxCeleb1, but I found that some of the details are missing.
Could you show us the exact parameters for finetuning, please?

Missing files are:
- audiossl/methods/atst/shell/downtream/finetune/eval_env.sh
- & eval_func.sh

And if you could, could you show me the parameter specifically for reproducing VC1 finetuning?
I was able to start training as follows, but with guessed parameters. I would need the right ones...

```sh
cd audiossl/methods/atst
python downstream/train_finetune.py --n_last_blocks 12 \
--pretrained_ckpt_path ./base.ckpt \
--save_path exp \
--learning_rate 5e-2 \
--max_epochs 50 \
--warmup_epochs 5 \
--dataset_name voxceleb1 \
--data_path /lab/data/voxceleb1 \
--batch_size 64
```

BTW, I'm sure your paper would have been accepted by Interspeech. I hope you could also update the arxiv comment to clarify.

Thank you.

**Comment by lmaxwell** [comment]
Hi, we are exciting that you are interesting in our work, especially you are the author of BYOL-A! 
I'm sorry the two files are missing. They are on my machine, but I forgot to upload them.  Now I have add them to main branch.
Note that I finetuned with batch size of 512 on all tasks. That is to say, if you use 1 gpu, then you should set batch size per gpu to 512.

**Comment by daisukelab** [comment]
Hi @lmaxwell 
Thank you for your quick work, I got missing files.
BTW, I found some issues in your paper. If you could fix them on the camera-ready version, that'd be better.
- Bootstrop you own latent" - typo.
- "window length of 25 ms" - it would be 64ms, as long as you are using a window size of 1024.
Anyway, I hope you enjoy Interspeech!
Thanks again!

**Comment by lilyzlt** [comment]
> ```shell
> --pretrained_ckpt_path ./base.ckpt 
> ```
where can I find this base model? thanks a lot
--pretrained_ckpt_path ./base.ckpt

**Comment by lmaxwell** [comment]
> > ```shell
> > --pretrained_ckpt_path ./base.ckpt 
> > ```
> 
> where can I find this base model? thanks a lot --pretrained_ckpt_path ./base.ckpt

Please visit the "Pretrained checkpoint" section on this page: [AudioSSL ATSTFrame README](https://github.com/Audio-WestlakeU/audiossl/blob/main/audiossl/methods/atstframe/README.md).
