### ISSUE TITLE
sorry, I want to know how to download the audioset?

### ISSUE THREAD

**Issue by liyunlongaaa** [Audio-WestlakeU/audiossl#7]
sorry to bother you, I only downloaded the tfrecord file on the audioset official website,  can i use it to do experiment? If it can't,  how can I download the audio file? thank you~

**Comment by lmaxwell** [comment]
Hi, sorry for the late response.   

It seems qiuqiang kong has uploaded all the audio files in Audioset to Baidu NetDisk( checkout README.md at https://github.com/qiuqiangkong/audioset_tagging_cnn).  I have not tried to download it , but there should be no problem.
